# wants: 
# homecoming living room nightlight
# Theatre lighting (drop to 10% when Chromecast plays, transition to off.  Raise to half when Chromecast paused, transition to
#    75% when night, 100% when not night)
# good night lights (transition after 8:00 to 9:15 to lower brightness on work nights)
# cloudy day lights (
# weather indicator light (orange for nice out, green for cold, blue for rain, pink for snow)
