#group:
#  living_room:
#    - light.table_lamp
#    - light.ceiling

#automation:
#  alias: Turn on light when sun sets
#  trigger:
#    platform: sun
#    event: sunset
#    offset: "-01:00:00"
#  condition:
#    platform: state
#    entity_id: group.all_devices
#    state: home
#  action:
#    service: light.turn_on
#    entity_id: group.living_room

# chromecast pause, lights are off, and it is evening

alias: 'Turn lights up when ChromeCast pauses or stops, evening'
trigger:
  
