alias: 'chrome_cast_on'
trigger: 
  platform: state
  entity_id: media_player.living_room
  to: playing
condition:
  platform: state
  entity_id: light.living_room
  state: 'on'
action:
  service: scene.turn_on
  entity_id: scene.living_room_low_lights
