alias: 'chromecast_off_night'
trigger: 
  platform: state
  entity_id: media_player.living_room
  from: playing
condition: 
  platform: time
  after: '21:00'
action:
  service: scene.turn_on
  entity_id: scene.living_room_mid_high_lights
