alias: 'Turn lights up when ChromeCast pauses or stops, night'
trigger: 
  platform: state
  entity_id: media_player.living_room
  from: playing
condition: 
  -platform: time
  after: '21:00'
action:
  service: homeassistant.turn_on
  entity_id: script.chrome_pause_stop_lights_night
