alias: 'Office Light on'
trigger:
  platform: sun
  event: 'sunset'
  offset: '-01:00:00' 
condition:
  platform: state
  entity_id: group.all_devices
  state: 'home'
action:
  service: light.turn_on
  entity_id: light.office_white
