alias: 'Office Light off'
trigger:
  - platform: sun
  event: 'sunrise'
  offset: '03:00:00' 
  - platform: state
  entity_id: group.all_devices
  state: 'home'
condition: use_trigger_values
action:
  service: light.turn_off
  entity_id: light.office_white
