alias: 'Rainy Day'
trigger:
  - platform: state
    entity_id: sensor.weather_precip
    state: 'rain'
  - platform: state
    entity_id: group.all_devices
    state: 'home'
  - platform: time
    after: '14:00'
    before: '23:00'
condition: use_trigger_values
action:
  service: light.turn_on
  entity_id: light.living_room
